FROM python:3.8-alpine

RUN apk add pkgconfig\
    alpine-sdk \
    ffmpeg-dev \
    libxslt-dev \
    libxml2-dev \
    autoconf \
    automake \
    freetype-dev \
    g++ \
    gcc \
    jpeg-dev \
    lcms2-dev \
    libffi-dev \
    libpng-dev \
    libwebp-dev \
    linux-headers \
    make \
    openjpeg-dev \
    libressl-dev \
    openssl-dev \
    python3-dev \
    tiff-dev \
    zlib-dev

RUN apk add postgresql-dev

WORKDIR /usr/src/webservice-graphql

COPY requirements3.txt .

RUN pip3 install -r requirements3.txt
RUN pip3 install autobahn[asyncio,encryption,serialization,xbr]
#RUN pip3 install git+git://github.com/graphql-python/graphene.git@d085c8852be40552428f74fdf891b20e54674540
COPY . .

